more cleanup; just test eskape

diff --git a/.github/workflows/unit-testing-conda.yml b/.github/workflows/unit-testing-conda.yml
--- a/.github/workflows/unit-testing-conda.yml
+++ b/.github/workflows/unit-testing-conda.yml
@@ -11,25 +11,25 @@ jobs:
         perl: [ '5.36.0' ]
         DATASET: 
           - datasets/eskape-amr.tsv
-          - datasets/campylobacter-pulsenet.tsv
-          - datasets/Campylobacter_jejuni_0810PADBR-1.tsv
        #  - datasets/Candida-auris-CladeI-1.tsv
-          - datasets/e.coli-Ahrenfeldt-dataset.tsv
-          - datasets/Escherichia_coli_1405WAEXK-1.tsv
-          - datasets/Listeria_monocytogenes_1408MLGX6-3WGS.tsv
-          - datasets/Litchfield.tsv
-          - datasets/PA_76_benchMarkInfo.tsv
        #  - datasets/Salmonella-AMR.tsv
-          - datasets/Salmonella_enterica_1203NYJAP-1.simulated.tsv
-          - datasets/Salmonella_enterica_1203NYJAP-1.tsv
-          - datasets/sars-cov-2-coronahit-rapid.tsv
-          - datasets/sars-cov-2-coronahit-routine-a.tsv
-          - datasets/sars-cov-2-coronahit-routine-b.tsv
-          - datasets/sars-cov-2-failedQC.tsv
-          - datasets/sars-cov-2-nonvoivoc.tsv
-          - datasets/sars-cov-2-SNF-A.tsv
-          - datasets/sars-cov-2-voivoc.tsv
-          - datasets/toy-bacteria-saureus.tsv
+       #  - datasets/campylobacter-pulsenet.tsv
+       #  - datasets/Campylobacter_jejuni_0810PADBR-1.tsv
+       #  - datasets/e.coli-Ahrenfeldt-dataset.tsv
+       #  - datasets/Escherichia_coli_1405WAEXK-1.tsv
+       #  - datasets/Listeria_monocytogenes_1408MLGX6-3WGS.tsv
+       #  - datasets/Litchfield.tsv
+       #  - datasets/PA_76_benchMarkInfo.tsv
+       #  - datasets/Salmonella_enterica_1203NYJAP-1.simulated.tsv
+       #  - datasets/Salmonella_enterica_1203NYJAP-1.tsv
+       #  - datasets/sars-cov-2-coronahit-rapid.tsv
+       #  - datasets/sars-cov-2-coronahit-routine-a.tsv
+       #  - datasets/sars-cov-2-coronahit-routine-b.tsv
+       #  - datasets/sars-cov-2-failedQC.tsv
+       #  - datasets/sars-cov-2-nonvoivoc.tsv
+       #  - datasets/sars-cov-2-SNF-A.tsv
+       #  - datasets/sars-cov-2-voivoc.tsv
+       #  - datasets/toy-bacteria-saureus.tsv
         NUM_PER_CHUNK:
           - 10
         # CHUNK is a set of numbers in increments of NUM_PER_CHUNK which exceeds the number
@@ -146,6 +146,11 @@ jobs:
             # Run the TAP compliant unit test(s) which reads env variable $DATASET
             bats t/*
             # some cleanup to help with space
-            find . -name '*.fastq' -delete || true
           fi
+      - name: Cleanup
+        run:  |
+          find . -name '*.fastq' -exec rm -vf {} \; || true
+          find . -name '*.fasta' -exec rm -vf {} \; || true
+          find . -name '*.gbk'   -exec rm -vf {} \; || true
+          find . -name '*.sra'   -exec rm -vf {} \; || true
 
