Eskape dataset (#18)
* fixed ; bugs, removed whitespace from strain; set default value for optional but required fields

* eskape dataset

* remove whitepsace and semicolons from strain names

* updated eskape spreadsheet with hashsums

* clean up space; put eskape up to the top for testing first

* more cleanup; just test eskape

* removed some genomes with very large file sizes

* uncomment

* removed some more SRRs that take up too much space

* a test to make sure it's just eskape that's causing problems

* systematically removed large runs

* fixed the spreadsheet

* removed a really large sample SRR8179283

* including all other datasets

* smaller chunks for testing to help with drive space

* reduce to just testing 40 per spreadsheet

diff --git a/.github/workflows/unit-testing-conda.yml b/.github/workflows/unit-testing-conda.yml
--- a/.github/workflows/unit-testing-conda.yml
+++ b/.github/workflows/unit-testing-conda.yml
@@ -10,15 +10,16 @@ jobs:
         os: ['ubuntu-20.04' ]
         perl: [ '5.36.0' ]
         DATASET: 
+          - datasets/eskape-amr.tsv
+          - datasets/Candida-auris-CladeI-1.tsv
+          - datasets/Salmonella-AMR.tsv
           - datasets/campylobacter-pulsenet.tsv
           - datasets/Campylobacter_jejuni_0810PADBR-1.tsv
-       #  - datasets/Candida-auris-CladeI-1.tsv
           - datasets/e.coli-Ahrenfeldt-dataset.tsv
           - datasets/Escherichia_coli_1405WAEXK-1.tsv
           - datasets/Listeria_monocytogenes_1408MLGX6-3WGS.tsv
           - datasets/Litchfield.tsv
           - datasets/PA_76_benchMarkInfo.tsv
-       #  - datasets/Salmonella-AMR.tsv
           - datasets/Salmonella_enterica_1203NYJAP-1.simulated.tsv
           - datasets/Salmonella_enterica_1203NYJAP-1.tsv
           - datasets/sars-cov-2-coronahit-rapid.tsv
@@ -30,11 +31,10 @@ jobs:
           - datasets/sars-cov-2-voivoc.tsv
           - datasets/toy-bacteria-saureus.tsv
         NUM_PER_CHUNK:
-          - 10
+          - 5
         # CHUNK is a set of numbers in increments of NUM_PER_CHUNK which exceeds the number
         # of samples in any given dataset.
-        CHUNK: [10,20,30,40,50,60,70,80,90,100,110,120]
-        #CHUNK: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40]
+        CHUNK: [5, 10, 15, 20, 25, 30, 35, 40]
     defaults:
       run:
         shell: bash -el {0}
@@ -145,4 +145,11 @@ jobs:
             # Run the TAP compliant unit test(s) which reads env variable $DATASET
             bats t/*
           fi
+      # some cleanup to help with space
+      - name: Cleanup
+        run:  |
+          find . -name '*.fastq' -exec rm -vf {} \; || true
+          find . -name '*.fasta' -exec rm -vf {} \; || true
+          find . -name '*.gbk'   -exec rm -vf {} \; || true
+          find . -name '*.sra'   -exec rm -vf {} \; || true
 
